config/routes.rb
Antarcticle::Application.routes.draw do

  resources :sessions, only: [:new, :create, :destroy]
  resources :articles do
    resources :comments, only: [:create, :update, :edit, :destroy]
  end

  root :to => 'articles#index'

  match '/signin', to: 'sessions#new'
  match '/signout', to: 'sessions#destroy', via: :delete

  match '/users/:username', to: 'users#show', as: :user, :username => /[^\/]*/

  match '/tags/:tags', to: 'tags#index', as: :tag, :tags => /.*/
  get '/tags_filter', to: 'tags#filter', as: :tags_filter
  match '/tags', to: redirect("/")
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  attr_accessible :content

  validates_presence_of :content
  validates_length_of :content, within: 1..32000
  validates_presence_of :user_id
  validates_presence_of :article_id

  #TODO avoid extra fetching
  default_scope includes(:user, :article).order('comments.created_at ASC')

  belongs_to :user
  belongs_to :article
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    authorize! :create, Comment
    @article = Article.find(params[:article_id])
    @comment = Comment.new(params[:comment])
    @comment.article = @article
    @comment.user = current_user
    if @comment.save
      redirect_to article_path(@article, anchor: "comment_#{@comment.id}")
    else
      #redirect_to article_path(@article, anchor: "comments")
      render 'articles/show'
    end
  end

  def update
    @comment = Comment.find(params[:id])
    authorize! :update, @comment

    if @comment.update_attributes(params[:comment])
      redirect_to article_path(params[:article_id], anchor: "comment_#{@comment.id}")
    else
      @article = Article.find(params[:article_id])
      render 'articles/show'
    end
  end

  def edit
    @comment_to_edit = Comment.find(params[:id])
    authorize! :update, @comment_to_edit
    @article = Article.find(params[:article_id])
    render 'articles/show'
  end

  def destroy
    @comment = Comment.find(params[:id])
    authorize! :destroy, @comment
    @comment.destroy

    redirect_to article_path(params[:article_id], anchor: "comments")
  end
end

app/views/comments/_comment.html.erb
<article class="comment comment-<%= if comment.user == comment.article.user then "author" else "other" end %>" id="comment_<%= comment.id %>">
  <div class="toolb">
    <% if can? :update, comment %>
      <%= link_to edit_article_comment_path(comment.article, comment, anchor: 'comments_form'), class: "btn btn-mini" do %>
        <i class="icon-pencil"></i>
      <% end %>
    <% end %>

    <% if can? :destroy, comment %>
      <%= link_to article_comment_path(comment.article, comment), class: "btn btn-mini btn-danger",
              method: :delete, confirm: "Are you sure you want to delete this comment?" do %>
        <i class="icon-remove"></i>
      <% end %>
    <% end %>
  </div>

  <div class="comment-bubble comment-bubble-<%= if comment.user == comment.article.user then "author" else "other" end %>">
    <header>
      <i class="icon-user"></i> <%= link_to comment.user.username, comment.user %>
      <time class="pull-right" datetime="<%= comment.created_at %>">
        <i class="icon-calendar"></i> <%= comment.created_at.strftime('%e %b %Y %H:%M') %>
      </time>
    </header>
    <div>
      <%= markdown comment.content %>
    </div>
  </div>
</article>

app/views/comments/_form.html.erb
<%= form_for([article, comment],
             url: if comment.new_record? then article_comments_path(article, anchor: "comments_form") else article_comment_path(article, comment, anchor: "comment_#{comment.id}") end,
             method: if comment.new_record? then :post else :put end,
             html: {
               id: "comments_form",
               class: "clearfix comment-bubble comment-bubble-#{if article.user == current_user then "author" else "other" end}"
             }) do |f| %>
  <%= errors_group comment %>
  <%= control_group comment, :content do %>
    <%= f.label :content, style: 'font-style: italic; font-size:11px' do %>
      Editor uses Markdown markup language. You can read reference <a href="https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet" target="_blank">here</a>.
    <% end %>
    <%= f.text_area :content, style: "width: 100%", rows: 10, placeholder: "Enter your comment here ..." %>
  <% end %>
  <%= f.submit "Post", class: "btn btn-primary pull-right" %>
<% end %>

app/views/comments/_list.html.erb
<section class="comments" id="comments">
  <h3 style="border-bottom: 1px dashed #646464">Comments</h3>

  <% if article.comments.any? %>
    <% for comment in article.comments %>
      <% if comment == @comment_to_edit %>
        <%= render 'comments/form', article: article, comment: comment %>
      <% else %>
        <%= render comment %>
      <% end %>
    <% end %>
  <% else %>
    <div class="centralized-inputs">
      <h3>There is no comments</h3>
    </div>
  <% end %>

  <% if @comment_to_edit.nil? %>
    <% if can? :create, Comment %>
      <%= render 'comments/form', article: article, comment: new_comment %>
    <% else %>
      <div class="centralized-inputs">
        Sign in to post comments
      </div>
    <% end %>
  <% end %>
</section>