config/routes.rb
Antarcticle::Application.routes.draw do

  resources :sessions, only: [:new, :create, :destroy]
  resources :articles do
    resources :comments, only: [:create, :update, :edit, :destroy]
  end

  root :to => 'articles#index'

  match '/signin', to: 'sessions#new'
  match '/signout', to: 'sessions#destroy', via: :delete

  match '/users/:username', to: 'users#show', as: :user, :username => /[^\/]*/

  match '/tags/:tags', to: 'tags#index', as: :tag, :tags => /.*/
  get '/tags_filter', to: 'tags#filter', as: :tags_filter
  match '/tags', to: redirect("/")
end

app/models/article.rb
class Article < ActiveRecord::Base
  include ApplicationHelper

  attr_accessible :content, :title, :description, :tag_list
  acts_as_taggable

  belongs_to :user

  before_save :create_description

  has_many :comments, dependent: :destroy

  validates :title, presence: true, length: { maximum: 60 }
  validates_length_of :content, maximum: 65000
  validates_presence_of :user_id
  validates_with TagsValidator

  default_scope order: 'articles.created_at DESC'

  def author_name
    user.username
  end

  def self.get_page(page)
    includes(:user, :tags).paginate(page: page, per_page: 10)
  end

  def self.get_page_tagged(page, tags)
    get_page(page).tagged_with(tags)
  end

  private
  def create_description
    self.description = helpers.truncate(helpers.strip_tags(markdown_render(self.content)), :length => 300)
  end

  def helpers
    ActionController::Base.helpers
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController

  def index
    authorize! :read, Article
    @articles = Article.get_page params[:page]
  end

  def show
    @article = Article.find(params[:id])
    authorize! :read, @article
    @comment = Comment.new
  end

  def new
    authorize! :create, Article
    @article = Article.new
  end

  def edit
    @article = Article.find(params[:id])
    authorize! :update, @article
  end

  def create
    authorize! :create, Article
    @article = current_user.articles.build(params[:article])

    if @article.save
      redirect_to @article, only_path: true, notice: 'Article was successfully created.'
    else
      render 'new'
    end
  end

  def update
    @article = Article.find(params[:id])
    authorize! :update, @article

    if @article.update_attributes(params[:article])
      redirect_to @article, notice: 'Article was successfully updated.'
    else
      render 'edit'
    end
  end

  def destroy
    @article = Article.find(params[:id])
    authorize! :destroy, @article
    @article.destroy

    redirect_to articles_url
  end
end

app/views/articles/_article.html.erb
<article id="<%= article.id %>" class="entry">
  <div class="main-content">
    <header>
      <div class="date">
        <span class="day"><%= l article.created_at, format: "%d" %></span>
        <span class="month"><%= l article.created_at, format: "%b" %></span>
        <span class="year"><%= l article.created_at, format: "%Y" %></span>
      </div>
      <h2><%= link_to article.title, article_path(article) %></h2>
    </header>

    <div class="body">
      <div class="content">
        <%= raw article.description %>
      </div>
      <%= link_to 'Read more', article_path(article), class: "read-more" %>
      <div class="clearfix"></div>
    </div>
  </div>

  <footer>
    <ul class="footer-elements">
      <li>
        <i class="icon-user"></i>
        <strong>by </strong>
        <%= link_to article.author_name, article.user %>
      </li>
      <li class="pull-right">
        <ul class="tags">
          <% article.tags.each do |tag| %>
            <li>
              <i class="icon-tags"></i><%= link_to tag, tag_path(tag) %>
            </li>
          <% end %>
        </ul>
      </li>
    </ul>
  </footer>

</article>

app/views/articles/_form.html.erb
<div class="row">
  <div class="hero-unit span7 offset2 well2">

    <header class="page-header">
      <h2><%= raw form_legend %></h2>
    </header>

    <% if article.errors.any? %>
      <div class="alert alert-error">
        <a class="close" data-dismiss="alert" href="#">×</a>
        <ul>
          <% article.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <%= form_for(article) do |f| %>
      <%= control_group article, :title do %>
        <%= f.text_field :title, class: "span7", placeholder: "Article title" %>
      <% end %>

      <%= control_group article, :content do %>
        <%= f.label :content, style: 'font-style: italic' do %>
          Editor uses Markdown markup language. You can read reference <a href="https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet" target="_blank">here</a>.
        <% end %>
        <%= f.text_area :content, class: "span7", rows: 25, placeholder: "Enter article content here ..." %>
      <% end %>

      <%= control_group article, :tag_list do %>
        <%= f.text_field :tag_list, class: "span7", placeholder: "Tags (separated by commas)" %>
      <% end %>

      <%= f.submit submit_text, class: "btn btn-primary btn-large pull-right" %>
    <% end %>
  </div>
</div>

app/views/articles/edit.html.erb
<% content_for(:title, "Editing article") %>
<%= render 'form',
  article: @article,
  form_legend: '<i class="icon-edit"></i> Editing article',
  submit_text: 'Edit article' %>

app/views/articles/index.html.erb
<% content_for(:title, "Articles") %>
<div class="row">
  <div class="span10 offset1">
    <div class="clearfix">
      <div class="pull-left" style="line-height:41px;margin-left:70px">
        <%= form_tag tags_filter_path, method: :get do %>
          <%= text_field_tag :tags, params[:tags], class: "span7", id: "tags_filter", placeholder: "Tags filter" %>
          <%= submit_tag 'Find', name: nil, class: "btn btn-info" %>
        <% end %>
      </div>

      <% if can? :create, Article %>
        <div class="pull-right">
          <%= link_to new_article_path, class: "btn btn-large btn-primary pull-right" do %>
            <i class="icon-pencil icon-white"></i> Write article
          <% end %>
          <div class="clearfix"></div>
        </div>
      <% end %>
    </div>

    <% if @articles.any? %>
      <section class="articles-list">
        <%= render @articles %>
      </section>
    <% else %>
      <div class="centralized-inputs" style="border: 1px dashed rgb(200, 200, 200);">
        <h3>There is no articles</h3>
      </div>
    <% end %>

    <%= will_paginate @articles %>
  </div>
</div>

app/views/articles/new.html.erb
<% content_for(:title, "New article") %>
<%= render 'form',
  article: @article,
  form_legend: '<i class="icon-pencil"></i> New article',
  submit_text: 'Post article'%>

app/views/articles/show.html.erb
<% content_for(:title, @article.title) %>

<div class="row">
  <div class="span10 offset1">
    <article id="<%= @article.id %>" class="entry">

      <div class="manage-buttons clearfix">
        <div class="pull-right">
          <% if can? :update, @article %>
            <%= link_to edit_article_path(@article), class: "btn btn-info" do %>
              <i class="icon-edit"></i> Edit
            <% end %>
          <% end %>

          <% if can? :destroy, @article %>
            <%= link_to article_path(@article), class: "btn btn-danger",
              method: :delete, confirm: "Are you sure you want to delete this article?" do %>
              <i class="icon-remove"></i> Delete
            <% end %>
          <% end %>
        </div>
      </div>

      <div class="main-content">
        <header>
          <div class="date">
            <span class="day"><%= l @article.created_at, format: "%d" %></span>
            <span class="month"><%= l @article.created_at, format: "%b" %></span>
            <span class="year"><%= l @article.created_at, format: "%Y" %></span>
          </div>
          <h2><%= @article.title %></h2>
        </header>

        <div class="body">
          <div class="content">
            <%= markdown @article.content %>
          </div>
          <div class="clearfix"></div>
        </div>
      </div>

      <footer>
        <ul class="footer-elements">
          <li>
            <i class="icon-user"></i>
            <strong>by </strong>
            <%= link_to @article.author_name, @article.user %>
          </li>
          <li class="pull-right">
            <ul class="tags">
              <% @article.tags.each do |tag| %>
                <li>
                  <i class="icon-tags"></i><%= link_to tag, tag_path(tag) %>
                </li>
              <% end %>
            </ul>
          </li>
        </ul>
      </footer>

    </article>

    <%= render 'comments/list', article: @article, new_comment: @comment %>

  </div>
</div>