config/routes.rb
Antarcticle::Application.routes.draw do

  resources :sessions, only: [:new, :create, :destroy]
  resources :articles do
    resources :comments, only: [:create, :update, :edit, :destroy]
  end

  root :to => 'articles#index'

  match '/signin', to: 'sessions#new'
  match '/signout', to: 'sessions#destroy', via: :delete

  match '/users/:username', to: 'users#show', as: :user, :username => /[^\/]*/

  match '/tags/:tags', to: 'tags#index', as: :tag, :tags => /.*/
  get '/tags_filter', to: 'tags#filter', as: :tags_filter
  match '/tags', to: redirect("/")
end

app/views/layouts/_flash_messages.html.erb
<% if flash.any? %>
    <div class="span10 offset1 global-block">
      <% flash.each do |key, value| %>
          <% if [:notice, :error, :info].include? key %>
              <% if key == :notice
                   key = :success
                 end %>
              <%= content_tag(:div, class: "alert alert-#{key}") do %>
                  <a class="close" data-dismiss="alert" href="#">×</a> <%= value %>
              <% end %>
          <% end %>
      <% end %>
    </div>
<% end %>

app/views/layouts/_footer.html.erb
<footer class="footer">
  <div class="span10 offset1 global-block">
    <span class="pull-left">Antarcticle project<br>© 2012 <a href="http://jtalks.org">jtalks.org</a></span>
    <span class="pull-right"><i class="icon-cogs"></i> Based on <a href="http://twitter.github.com/bootstrap/">Bootstrap</a></span>
  </div>
</footer>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-inverse nav">
  <div class="navbar-inner">
    <div class="span10 offset1 global-block">
      <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </a>
      <%= link_to root_path, class: "brand" do %>
        <i class="icon-book"></i> <%= CONFIG["title"] || "Antarcticle" %>
      <% end %>
      <div class="nav-collapse collapse">
        <% if CONFIG.has_key? "menu" %>
          <ul class="nav custom-menu">
            <li class="divider-vertical"></li>
            <% CONFIG["menu"].each do |entry| %>
              <li>
                <%= link_to entry["name"], entry["url"] %>
              </li>
              <li class="divider-vertical"></li>
            <% end %>
          </ul>
        <% end %>
        <div class="pull-right">
          <ul class="nav pull-right">
            <% if signed_in? %>
                <li class="dropdown"><a href="#" class="dropdown-toggle" data-toggle="dropdown">Welcome, <%= current_user.username %> <b class="caret"></b></a>
                  <ul class="dropdown-menu">
                    <li>
                      <%= link_to user_path(current_user) do %>
                          <i class="icon-file"></i> My articles
                      <% end %>
                    </li>
                    <li class="divider"></li>
                    <li>
                      <%= link_to signout_path, method: "delete" do %>
                          <i class="icon-signout"></i> Sign out
                      <% end %>
                    </li>
                  </ul>
                </li>
            <% else %>
                <li>
                  <%= link_to signin_path do %>
                      <i class="icon-signin icon-white"></i> Sign in
                  <% end %>
                </li>
            <% end %>
          </ul>
        </div>
      </div>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <!--[if lt IE 9]>
    <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
  <![endif]-->
  <title><%= CONFIG["title"] || "Antarcticle" %> - <%= yield_for(:title, "Articles") %></title>
</head>
<body>
    <div id="page-wrapper">
        <%= render 'layouts/header' %>

        <div id="main-container" class="container">
          <%= render 'layouts/flash_messages' %>

          <%= yield %>
        </div>

        <%= render 'layouts/footer' %>
    </div>
</body>
</html>